#ifndef __PTA_HELLO_WORLD_H
#define __PTA_HELLO_WORLD_H

#define PTA_HELLO_WORLD_UUID \
		{ 0x12345678, 0xc3e5, 0x21e3, \
			{ 0x87, 0x94, 0x10, 0x02, 0xa5, 0xd5, 0xc6, 0x1b } }

#define PTA_HELLO_WORLD_SAY_HI 0

#define PTA_HELLO_WORLD_TEST_NO_PARAMS 1

#define PTA_HELLO_WORLD_TEST_IN_VALUE_PARAMS 2

#define PTA_HELLO_WORLD_TEST_IN_MEMREF_PARAMS 3

#define PTA_HELLO_WORLD_TEST_OUT_VALUE_PARAMS 4

#define PTA_HELLO_WORLD_TEST_OUT_MEMREF_PARAMS 5

#define PTA_HELLO_WORLD_TEST_GET_REE_TIME 6

#endif /*__PTA_HELLO_WORLD_H*/
